apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-notification-service
  template:
    metadata:
      labels:
        app: email-notification-service
    spec:
      containers:
        - name: email-notification-service
          image: email-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: SERVER_PORT
              value: "8082"

            - name: MOVIE_SERVICE_URL
              value: "http://movie-service:80/api/movie"

            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://elasticsearch:9200"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"

            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 10