apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-notification-service
  template:
    metadata:
      labels:
        app: email-notification-service
    spec:
      containers:
        - name: email-notification-service
          image: email-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://elasticsearch:9200"
            - name: MOVIE_SERVICE_URL
              value: "http://movie-service:80/api/movie"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-notification-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-notification-secrets
                  key: MAIL_PASSWORD
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: email-notification-secrets
                  key: ELASTIC_USER
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_USE_TYPE_HEADERS
              value: "false"
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10