apiVersion: v1
kind: Service
metadata:
  name: email-notification-service
spec:
  type: ClusterIP
  selector:
    app: email-notification-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082