apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinema-app

resources:
  - namespace.yml
  - postgresql
  - movie-session-service
  - mongodb
  - elasticsearch
  - kafka
  - api-gateway
  - movie-service
  - frontend-service
  - email-notification-service
  - ingress