apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-session-service
  template:
    metadata:
      labels:
        app: movies-session-service
    spec:
      containers:
        - name: movies-session-service
          # Логічне ім'я для Kustomize
          image: movies-session-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_ADDRESS
              value: mongodb://mongo:27017/movie-session-db
            - name: MOVIE_SERVICE_URL
              value: http://localhost:8080/api/movie
            - name: SERVICE_NAME
              value: movie-session-service
          readinessProbe:
            httpGet:
              path: /health
              port: 3500
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3500
            initialDelaySeconds: 30
            periodSeconds: 20