apiVersion: v1
kind: Service
metadata:
  name: movie-session-service
spec:
  type: ClusterIP
  selector:
    app: movie-session-service
  ports:
    - name: http
      port: 3500
      targetPort: 3500